### ISSUE TITLE
Adapt InverseKinematics using custom code

### ISSUE THREAD

**Issue by AurelienRenou** [Ipuch/bioptim_exo#5]
Create a condition to allow user to chose between kalman filter and IPOPT

**Comment by Ipuch** [comment]
Can you work with Thasaarah to generate the new generalized coordinates "q" from the InverseKinematics class you generated with biorbd for all the tasks?

**Comment by Ipuch** [comment]
@AurelienRenou up

**Comment by Ipuch** [comment]
done in #24
